### ISSUE TITLE
Code clarification

### ISSUE THREAD

**Issue by 21212124** [cezane/optee_rsa_example#1]
Hi @cezane,

I have tested your code, could you explain to me to understand it better how it works?
Encrypts in CA and saves them in TA and then decrypts in CA?
I also see that with fflush it writes in the output the traceability of the system calls, right?
Your code is very useful, thanks

**Comment by cezane** [comment]
Hello, @21212124 .
This code only demonstrates how the RSA methods work in the Trusted World. In the CA I send a string to be encrypted in the TA, showing the result after the encryption process. Then, I pass the encrypted string back to the TA, to decrypt it there, showing again the original string.

If you have some specific doubt, let me know and I try to help.

**Comment by 21212124** [comment]
Hi @cezane ,
Where are the key pair stored? in TA? I understand that the public key can be known but the private one remains hidden in TA?

Another question, how does the CA know which key pair you have to use to encrypt and decrypt? Could an attacker use another key pair?

thanks for helping me, it's very interesting

**Comment by cezane** [comment]
The keys are generated inside the TA. The application does not perform keys exchange. The key pair remains secure in the TA memory. This is a simple application to only test the RSA encryption/decryption processes. 

If you need to apply this code in some application, you can get the public key and send it for interested entities. These entities will be able to perform data encryption with the receive public key and data will be only decrypted inside TA.
